/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui_patient;

import java.awt.CardLayout;
import javax.swing.JPanel;
import medicalsystem.EncounterHistory;
import medicalsystem.MedicalSystem;
import medicalsystem.User;
import ui_encounter.EncounterHistoryJPanel;

/**
 *
 * @author Jianpeng Ji
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    private JPanel userProcessContainer;
    private MedicalSystem admin;
    private User user;
    private EncounterHistory encounterHistory;

    public PatientJPanel(JPanel userProcessContainer, MedicalSystem admin, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.admin = admin;
        this.user = user;
        this.encounterHistory = new EncounterHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonEncounterHistory = new javax.swing.JButton();
        jButtonRequestHistory = new javax.swing.JButton();

        jButton1.setText("View Doctors for Diagnosis ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonEncounterHistory.setText("Encounter History");
        jButtonEncounterHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncounterHistoryActionPerformed(evt);
            }
        });

        jButtonRequestHistory.setText("Request History");
        jButtonRequestHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRequestHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonRequestHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DiagnosisRequestJPanel requestDiagnosis = new DiagnosisRequestJPanel(userProcessContainer, admin, user);
        userProcessContainer.add("PatientsForDiagnosisJPanel", requestDiagnosis);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEncounterHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncounterHistoryActionPerformed
        // TODO add your handling code here:
        EncounterHistoryJPanel encounterHistory = new EncounterHistoryJPanel(userProcessContainer, admin, user);
        userProcessContainer.add("EncounterHistoryJPanel", encounterHistory);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_jButtonEncounterHistoryActionPerformed

    private void jButtonRequestHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestHistoryActionPerformed
        // TODO add your handling code here:
        RequestHistoryJPanel requestHistory = new RequestHistoryJPanel(userProcessContainer, admin, user);
        userProcessContainer.add("EncounterHistoryJPanel", requestHistory);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonRequestHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEncounterHistory;
    private javax.swing.JButton jButtonRequestHistory;
    // End of variables declaration//GEN-END:variables
}
